import React from "react";
import { Copyright, Calendar, Mail, AlertTriangle } from "lucide-react";

export default function DMCAPage() {
  return (
    <div className="space-y-8 text-muted-foreground">
      <div className="space-y-4">
        <h1 className="text-3xl font-bold text-primary mb-2">DMCA & Copyright Policy</h1>
        <div className="flex items-center gap-4 text-sm">
          <span className="flex items-center gap-2">
            <Calendar className="w-4 h-4" />
            Last Updated: January 7, 2026
          </span>
        </div>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
          <Copyright className="w-5 h-5 text-primary" />
          1. Copyright Statement
        </h2>
        <p>
          MALOLA respects the intellectual property rights of others and expects our users to do the same. We are committed to responding to notices of alleged copyright infringement that comply with applicable laws.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">2. Our Content</h2>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li><strong>Ancient Scriptures:</strong> Original Sanskrit/Pali texts are in the public domain. Our translations and commentary are original works.</li>
          <li><strong>Platform Design:</strong> All logos, icons, and UI elements are copyrighted by MALOLA.</li>
          <li><strong>AI-Generated Content:</strong> Unique explanations and insights generated by our AI are proprietary.</li>
          <li><strong>User Content:</strong> Users retain copyright to their own contributions.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">3. DMCA Takedown Procedure</h2>
        <p>
          If you believe that content on MALOLA infringes your copyright, please send a notification containing:
        </p>
        <ol className="list-decimal list-inside space-y-2 ml-4">
          <li>Your physical or electronic signature</li>
          <li>Identification of the copyrighted work claimed to be infringed</li>
          <li>Identification of the infringing material and its location on our platform</li>
          <li>Your contact information (address, phone, email)</li>
          <li>A statement that you have a good faith belief that the use is not authorized</li>
          <li>A statement, under penalty of perjury, that the information is accurate and you are authorized to act on behalf of the copyright owner</li>
        </ol>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
          <AlertTriangle className="w-5 h-5 text-amber-500" />
          4. Counter-Notification
        </h2>
        <p>
          If you believe your content was wrongly removed, you may submit a counter-notification containing:
        </p>
        <ol className="list-decimal list-inside space-y-2 ml-4">
          <li>Your physical or electronic signature</li>
          <li>Identification of the removed material and its prior location</li>
          <li>A statement under penalty of perjury that the removal was a mistake</li>
          <li>Your name, address, and phone number</li>
          <li>A statement consenting to jurisdiction of the federal court in your district</li>
        </ol>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">5. Repeat Infringers</h2>
        <p>
          In accordance with the DMCA, we will terminate user accounts of repeat infringers in appropriate circumstances.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">6. Fair Use</h2>
        <p>
          MALOLA supports fair use of copyrighted material for purposes such as criticism, comment, teaching, scholarship, and research. We consider fair use factors when evaluating DMCA claims.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">7. Attribution</h2>
        <p>
          We strive to properly attribute all content on our platform. If you are a translator, scholar, or content creator whose work appears on MALOLA and you believe attribution is missing or incorrect, please contact us.
        </p>
      </section>

      <section className="space-y-3 p-4 bg-primary/10 rounded-lg border border-primary/20">
        <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
          <Mail className="w-5 h-5" />
          DMCA Agent
        </h2>
        <p>
          Send DMCA notices and counter-notifications to our designated agent:
        </p>
        <div className="mt-3 space-y-1 text-foreground">
          <p className="font-medium">MALOLA DMCA Agent</p>
          <p>Email: dmca@malola.app</p>
        </div>
      </section>
    </div>
  );
}
